language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: RJAZ2xSbqVIj672vT4vLL5l06B7Nca+WsPJJUZ/jtwAq7Qw7xgYGGsEFBE9KaPE2YF30vjcbp7JHfrn2guhWAn4jpEQEOQ0y7rT1l4Ytj94hCoBHGgUlV17bZBVQ4ndNDODEYTM9lwFL9MlCq0513dufV/bcOY7iUvOSGj5cfIXFpwMIqf6Lq3ZWE1UNTs9HJaI7fhRxscjeXg7S+pd9H3V4KCogPtDr1ZyZQ7HVWEDkdoyDWPkuElYTB6Rb81/eqmEDvoKlR8h7a1KxT5MgsHCovKsgDcDjzy5aeZSr8J69D7nNYbYOqTR/1ftgytnAfZprfda9I+bLK2xbXEVptXG15093Zt2GBptgZ1OrRwLBFfvV79eZX3bL/14Oyt+X4SSRsrGu2W9SmnsyV0h1S4twHMxkaHCTl3KS5JO0RohRMnB90jU8Vr0Jfj/6FvZr5ezkxjW09NnBvqqQcVJqJ1t2xRv2mSZtlNxjicIvXmTUMY0l8A+gKl4KpCvBPfgzWjdqNmd0KrAXHt3HJmoD7VV1ofDauYqKdYsE2uiZ8i38USn20jtyvfdW/+rzlblhJBQAPyCZEFOEMSyl68RmgSE8tXXrY3ot4MxwZi+1CUj412UDgAUeIjPm82BccCIXzfOUh2T43miHQ7pD2F4JZwKxP+bmbssnwsb6b18W2F8=
