language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: mZsKafLzTddh1RB3xXJCbx4txdRJA3YanIsKoMvMp8cruh0jVCL9vLCqOXdWvYEHR/1MNGKiXU4d5TVXXJlhVM046yS1qax2tjXXGhNfANYonZWDfEXRXsrra1NqbvuRaINhklBwFBEQgNCP0cbdmtNla8Xhm4R6bzk6MQqbwboazlXmYEGnnRxHxutOUtOgP7h4bEXAM6vhNFXpXRTLQkB3EsNflf6S4G5LpfNyniS0Aao0+NIB5NSZ2IkRLifuxIMbXxQ30pXjvhKLVi1ysHCugO8WIcZcLb5Tgy4F5BZIQaegej8OaduA/8QYjuQhu1rxDa7YvzJLiOL0XosZ3+Njxuig8J/4Nb29GCXuOhcRln4OCMqkPa4rBSiJXkW4M6ROTOuntEVS3AxxrRYlqWUttxcKWbgvxzhMwbOxN8W2KyAR7WC4lKrFO08XW3Ns/WJC8C5BzARrS+c4SFl3gXTs9Fn1R77QhULJuPwc5gz2PelOv4ewOc3cBwDuOu24z8hdVI7KgRHtfV0TrK4bz21Ob051eapFM3fv0UVYJ0EunkFDuT77JEutqiGiUiIpPDQBayiK8VNIcvQzE5MqYZT4lzHz18hq3joOAdNaF66k4dfa+COcG5H2lAJIpujLogWb+mG6YmYS0dSJMJXxbIjLaI8tv26UhCJNVnj71kQ=
